export const data = [
    {id: 1, name: "Bulbasaur", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/001.png"},
    {id: 2, name: "Ivysaur", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/002.png"},
    {id: 3, name: "Venusaur", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/003.png"},
    {id: 4, name: "Charmander", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/004.png"},
    {id: 5, name: "Charmeleon", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/005.png"},
    {id: 6, name: "Charizard", tipo: ["Fogo", "Voador"], fraqueza: ["Agua", "Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/006.png"},
    {id: 7, name: "Squirtle", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/007.png"},
    {id: 8, name: "Wartortle", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/008.png"},
    {id: 9, name: "Blastoise", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/009.png"},
    {id: 10, name: "Caterpie", tipo: ["Inseto"], fraqueza: ["Fogo", "Voador", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/010.png"},
    {id: 11, name: "Metapod", tipo: ["Inseto"], fraqueza: ["Fogo", "Voador", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/011.png"},
    {id: 12, name: "Butterfree", tipo: ["Inseto", "Voador"], fraqueza: ["Fogo", "Elétrico", "Gelo", "Voador", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/012.png"},
    {id: 13, name: "Weedle", tipo: ["Inseto", "Venenoso"], fraqueza: ["Fogo", "Voador", "Psiquico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/013.png"},
    {id: 14, name: "Kakuna", tipo: ["Inseto", "Venenoso"], fraqueza: ["Fogo", "Voador", "Psiquico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/014.png"},
    {id: 15, name: "Beedrill", tipo: ["Inseto", "Venenoso"], fraqueza: ["Fogo", "Voador", "Psiquico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/015.png"},
    {id: 16, name: "Pidgey", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/016.png"},
    {id: 17, name: "Pidgeotto", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/017.png"},
    {id: 18, name: "Pidgeot", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/018.png"},
    {id: 19, name: "Rattata", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/019.png"},
    {id: 20, name: "Raticate", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/020.png"},
    {id: 21, name: "Spearow", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/021.png"},
    {id: 22, name: "Fearow", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/022.png"},
    {id: 23, name: "Ekans", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/023.png"},
    {id: 24, name: "Arbok", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/024.png"},
    {id: 25, name: "Pikachu", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/025.png"},
    {id: 26, name: "Raichu", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/026.png"},
    {id: 27, name: "Sandshrew", tipo: ["Terra"], fraqueza: ["Agua", "Planta", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/027.png"},
    {id: 28, name: "Sandslash", tipo: ["Terra"], fraqueza: ["Agua", "Planta", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/028.png"},
    {id: 29, name: "Nidoran♀", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/029.png"},
    {id: 30, name: "Nidorina", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/030.png"},
    {id: 31, name: "Nidoqueen", tipo: ["Venenoso", "Terra"], fraqueza: ["Agua", "Gelo", "Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/031.png"},
    {id: 32, name: "Nidoran♂", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/032.png"},
    {id: 33, name: "Nidorino", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/033.png"},
    {id: 34, name: "Nidoking", tipo: ["Venenoso", "Terra"], fraqueza: ["Agua", "Gelo", "Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/034.png"},
    {id: 35, name: "Clefairy", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/035.png"},
    {id: 36, name: "Clefable", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/036.png"},
    {id: 37, name: "Vulpix", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/037.png"},
    {id: 38, name: "Ninetales", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/038.png"},
    {id: 39, name: "Jigglypuff", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/039.png"},
    {id: 40, name: "Wigglytuff", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/040.png"},
    {id: 41, name: "Zubat", tipo: ["Venenoso", "Voador"], fraqueza: ["Elétrico", "Gelo", "Psiquico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/041.png"},
    {id: 42, name: "Golbat", tipo: ["Venenoso", "Voador"], fraqueza: ["Elétrico", "Gelo", "Psiquico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/042.png"},
    {id: 43, name: "Oddish", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/043.png"},
    {id: 44, name: "Gloom", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/044.png"},
    {id: 45, name: "Vileplume", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/045.png"},
    {id: 46, name: "Paras", tipo: ["Inseto", "Planta"], fraqueza: ["Fogo", "Gelo", "Voador", "Venenoso", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/046.png"},
    {id: 47, name: "Parasect", tipo: ["Inseto", "Planta"], fraqueza: ["Fogo", "Gelo", "Voador", "Venenoso", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/047.png"},
    {id: 48, name: "Venonat", tipo: ["Inseto", "Venenoso"], fraqueza: ["Fogo", "Voador", "Psiquico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/048.png"},
    {id: 49, name: "Venomoth", tipo: ["Inseto", "Venenoso"], fraqueza: ["Fogo", "Voador", "Psiquico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/049.png"},
    {id: 50, name: "Diglett", tipo: ["Terra"], fraqueza: ["Agua", "Planta", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/050.png"},
    {id: 51, name: "Dugtrio", tipo: ["Terra"], fraqueza: ["Agua", "Planta", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/051.png"},
    {id: 52, name: "Meowth", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/052.png"},
    {id: 53, name: "Persian", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/053.png"},
    {id: 54, name: "Psyduck", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/054.png"},
    {id: 55, name: "Golduck", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/055.png"},
    {id: 56, name: "Mankey", tipo: ["Luta"], fraqueza: ["Psiquico", "Voador"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/056.png"},
    {id: 57, name: "Primeape", tipo: ["Luta"], fraqueza: ["Psiquico", "Voador"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/057.png"},
    {id: 58, name: "Growlithe", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/058.png"},
    {id: 59, name: "Arcanine", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/059.png"},
    {id: 60, name: "Poliwag", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/060.png"},
    {id: 61, name: "Poliwhirl", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/061.png"},
    {id: 62, name: "Poliwrath", tipo: ["Agua", "Luta"], fraqueza: ["Elétrico", "Planta", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/062.png"},
    {id: 63, name: "Abra", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/063.png"},
    {id: 64, name: "Kadabra", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/064.png"},
    {id: 65, name: "Alakazam", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/065.png"},
    {id: 66, name: "Machop", tipo: ["Luta"], fraqueza: ["Psiquico", "Voador"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/066.png"},
    {id: 67, name: "Machoke", tipo: ["Luta"], fraqueza: ["Psiquico", "Voador"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/067.png"},
    {id: 68, name: "Machamp", tipo: ["Luta"], fraqueza: ["Psiquico", "Voador"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/068.png"},
    {id: 69, name: "Bellsprout", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/069.png"},
    {id: 70, name: "Weepinbell", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/070.png"},
    {id: 71, name: "Victreebel", tipo: ["Planta", "Venenoso"], fraqueza: ["Fogo", "Gelo", "Voador", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/071.png"},
    {id: 72, name: "TentAçool", tipo: ["Agua", "Venenoso"], fraqueza: ["Elétrico", "Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/072.png"},
    {id: 73, name: "Tentacruel", tipo: ["Agua", "Venenoso"], fraqueza: ["Elétrico", "Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/073.png"},
    {id: 74, name: "Geodude", tipo: ["Pedra", "Terra"], fraqueza: ["Agua", "Planta", "Gelo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/074.png"},
    {id: 75, name: "Graveler", tipo: ["Pedra", "Terra"], fraqueza: ["Agua", "Planta", "Gelo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/075.png"},
    {id: 76, name: "Golem", tipo: ["Pedra", "Terra"], fraqueza: ["Agua", "Planta", "Gelo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/076.png"},
    {id: 77, name: "Ponyta", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/077.png"},
    {id: 78, name: "Rapidash", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/078.png"},
    {id: 79, name: "Slowpoke", tipo: ["Agua", "Psiquico"], fraqueza: ["Elétrico", "Planta", "Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/079.png"},
    {id: 80, name: "Slowbro", tipo: ["Agua", "Psiquico"], fraqueza: ["Elétrico", "Planta", "Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/080.png"},
    {id: 81, name: "Magnemite", tipo: ["Elétrico", "Aço"], fraqueza: ["Fogo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/081.png"},
    {id: 82, name: "Magneton", tipo: ["Elétrico", "Aço"], fraqueza: ["Fogo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/082.png"},
    {id: 83, name: "Farfetch'd", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/083.png"},
    {id: 84, name: "Doduo", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/084.png"},
    {id: 85, name: "Dodrio", tipo: ["Normal", "Voador"], fraqueza: ["Elétrico", "Pedra", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/085.png"},
    {id: 86, name: "Seel", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/086.png"},
    {id: 87, name: "Dewgong", tipo: ["Agua", "Gelo"], fraqueza: ["Elétrico", "Planta", "Luta", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/087.png"},
    {id: 88, name: "Grimer", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/088.png"},
    {id: 89, name: "Muk", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/089.png"},
    {id: 90, name: "Shellder", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/090.png"},
    {id: 91, name: "Cloyster", tipo: ["Agua", "Gelo"], fraqueza: ["Elétrico", "Planta", "Luta", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/091.png"},
    {id: 92, name: "Gastly", tipo: ["Fantasma", "Venenoso"], fraqueza: ["Terra", "Psiquico", "Fantasma"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/092.png"},
    {id: 93, name: "Haunter", tipo: ["Fantasma", "Venenoso"], fraqueza: ["Terra", "Psiquico", "Fantasma"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/093.png"},
    {id: 94, name: "Gengar", tipo: ["Fantasma", "Venenoso"], fraqueza: ["Terra", "Psiquico", "Fantasma"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/094.png"},
    {id: 95, name: "Onix", tipo: ["Pedra", "Terra"], fraqueza: ["Agua", "Planta", "Gelo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/095.png"},
    {id: 96, name: "Drowzee", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/096.png"},
    {id: 97, name: "Hypno", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/097.png"},
    {id: 98, name: "Krabby", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/098.png"},
    {id: 99, name: "Kingler", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/099.png"},
    {id: 100, name: "Voltorb", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/100.png"},
    {id: 101, name: "Electrode", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/101.png"},
    {id: 102, name: "Exeggcute", tipo: ["Planta", "Psiquico"], fraqueza: ["Fogo", "Gelo", "Voador", "Venenoso", "Inseto", "Fantasma"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/102.png"},
    {id: 103, name: "Exeggutor", tipo: ["Planta", "Psiquico"], fraqueza: ["Fogo", "Gelo", "Voador", "Venenoso", "Inseto", "Fantasma"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/103.png"},
    {id: 104, name: "Cubone", tipo: ["Terra"], fraqueza: ["Agua", "Planta", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/104.png"},
    {id: 105, name: "Marowak", tipo: ["Terra"], fraqueza: ["Agua", "Planta", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/105.png"},
    {id: 106, name: "Hitmonlee", tipo: ["Luta"], fraqueza: ["Psiquico", "Voador"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/106.png"},
    {id: 107, name: "Hitmonchan", tipo: ["Luta"], fraqueza: ["Psiquico", "Voador"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/107.png"},
    {id: 108, name: "Lickitung", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/108.png"},
    {id: 109, name: "Koffing", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/109.png"},
    {id: 110, name: "Weezing", tipo: ["Venenoso"], fraqueza: ["Terra", "Psiquico"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/110.png"},
    {id: 111, name: "Rhyhorn", tipo: ["Terra", "Pedra"], fraqueza: ["Agua", "Planta", "Gelo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/111.png"},
    {id: 112, name: "Rhydon", tipo: ["Terra", "Pedra"], fraqueza: ["Agua", "Planta", "Gelo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/112.png"},
    {id: 113, name: "Chansey", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/113.png"},
    {id: 114, name: "Tangela", tipo: ["Planta"], fraqueza: ["Fogo", "Gelo", "Voador", "Venenoso", "Inseto"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/114.png"},
    {id: 115, name: "Kangaskhan", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/115.png"},
    {id: 116, name: "Horsea", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/116.png"},
    {id: 117, name: "Seadra", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/117.png"},
    {id: 118, name: "Goldeen", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/118.png"},
    {id: 119, name: "Seaking", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/119.png"},
    {id: 120, name: "Staryu", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/120.png"},
    {id: 121, name: "Starmie", tipo: ["Agua", "Psiquico"], fraqueza: ["Elétrico", "Planta", "Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/121.png"},
    {id: 122, name: "Mr. Mime", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/122.png"},
    {id: 123, name: "Scyther", tipo: ["Inseto", "Voador"], fraqueza: ["Fogo", "Elétrico", "Gelo", "Voador", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/123.png"},
    {id: 124, name: "Jynx", tipo: ["Gelo", "Psiquico"], fraqueza: ["Fogo", "Pedra", "Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/124.png"},
    {id: 125, name: "Electabuzz", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/125.png"},
    {id: 126, name: "Magmar", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/126.png"},
    {id: 127, name: "Pinsir", tipo: ["Inseto"], fraqueza: ["Fogo", "Voador", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/127.png"},
    {id: 128, name: "Tauros", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/128.png"},
    {id: 129, name: "Magikarp", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/129.png"},
    {id: 130, name: "Gyarados", tipo: ["Agua", "Voador"], fraqueza: ["Elétrico", "Planta", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/130.png"},
    {id: 131, name: "Lapras", tipo: ["Agua", "Gelo"], fraqueza: ["Elétrico", "Planta", "Luta", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/131.png"},
    {id: 132, name: "Ditto", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/132.png"},
    {id: 133, name: "Eevee", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/133.png"},
    {id: 134, name: "Vaporeon", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/134.png"},
    {id: 135, name: "Jolteon", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/135.png"},
    {id: 136, name: "Flareon", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/136.png"},
    {id: 137, name: "Porygon", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/137.png"},
    {id: 138, name: "Omanyte", tipo: ["Agua", "Pedra"], fraqueza: ["Elétrico", "Planta", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/138.png"},
    {id: 139, name: "Omastar", tipo: ["Agua", "Pedra"], fraqueza: ["Elétrico", "Planta", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/139.png"},
    {id: 140, name: "Kabuto", tipo: ["Agua", "Pedra"], fraqueza: ["Elétrico", "Planta", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/140.png"},
    {id: 141, name: "Kabutops", tipo: ["Agua", "Pedra"], fraqueza: ["Elétrico", "Planta", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/141.png"},
    {id: 142, name: "Aerodactyl", tipo: ["Pedra", "Voador"], fraqueza: ["Elétrico", "Gelo", "Agua", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/142.png"},
    {id: 143, name: "Snorlax", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/143.png"},
    {id: 144, name: "Articuno", tipo: ["Gelo", "Voador"], fraqueza: ["Elétrico", "Fogo", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/144.png"},
    {id: 145, name: "Zapdos", tipo: ["Elétrico", "Voador"], fraqueza: ["Gelo", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/145.png"},
    {id: 146, name: "Moltres", tipo: ["Fogo", "Voador"], fraqueza: ["Agua", "Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/146.png"},
    {id: 147, name: "Dratini", tipo: ["Dragão"], fraqueza: ["Gelo", "Dragão"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/147.png"},
    {id: 148, name: "Dragonair", tipo: ["Dragão"], fraqueza: ["Gelo", "Dragão"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/148.png"},
    {id: 149, name: "Dragonite", tipo: ["Dragão", "Voador"], fraqueza: ["Gelo", "Pedra", "Dragão"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/149.png"},
    {id: 150, name: "Mewtwo", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/150.png"},
    {id: 151, name: "Mew", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/151.png"},
    {id: 229, name: "Houndoom", tipo: ["Sombrio", "Fogo"], fraqueza: ["Agua", "Pedra", "Terra", "Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/229.png"},
    {id: 405, name: "Luxray", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/405.png"},
    {id: 243, name: "Raikou", tipo: ["Elétrico"], fraqueza: ["Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/243.png"},
    {id: 244, name: "Entei", tipo: ["Fogo"], fraqueza: ["Agua", "Terra", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/244.png"},
    {id: 245, name: "Suicune", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/245.png"},
    {id: 249, name: "Lugia", tipo: ["Psiquico", "Voador"], fraqueza: ["Elétrico", "Gelo", "Pedra", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/249.png"},
    {id: 250, name: "Ho-Oh", tipo: ["Fogo", "Voador"], fraqueza: ["Agua", "Elétrico", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/250.png"},
    {id: 377, name: "Regirock", tipo: ["Pedra"], fraqueza: ["Agua", "Planta", "Luta", "Terra", "Aço"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/377.png"},
    {id: 378, name: "Regice", tipo: ["Gelo"], fraqueza: ["Fogo", "Luta", "Pedra", "Aço"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/378.png"},
    {id: 379, name: "Registeel", tipo: ["Aço"], fraqueza: ["Fogo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/379.png"},
    {id: 380, name: "Latias", tipo: ["Dragão", "Psiquico"], fraqueza: ["Gelo", "Inseto", "Fantasma", "Dragão", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/380.png"},
    {id: 381, name: "Latios", tipo: ["Dragão", "Psiquico"], fraqueza: ["Gelo", "Inseto", "Fantasma", "Dragão", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/381.png"},
    {id: 382, name: "Kyogre", tipo: ["Agua"], fraqueza: ["Elétrico", "Planta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/382.png"},
    {id: 383, name: "Groudon", tipo: ["Terra"], fraqueza: ["Agua", "Planta", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/383.png"},
    {id: 384, name: "Rayquaza", tipo: ["Dragão", "Voador"], fraqueza: ["Gelo", "Pedra", "Dragão"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/384.png"},
    {id: 480, name: "Uxie", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/480.png"},
    {id: 481, name: "Mesprit", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/481.png"},
    {id: 482, name: "Azelf", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/482.png"},
    {id: 483, name: "Dialga", tipo: ["Aço", "Dragão"], fraqueza: ["Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/483.png"},
    {id: 484, name: "Palkia", tipo: ["Agua", "Dragão"], fraqueza: ["Dragão", "Fada"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/484.png"},
    {id: 485, name: "Heatran", tipo: ["Fogo", "Aço"], fraqueza: ["Agua", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/485.png"},
    {id: 486, name: "Regigigas", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/486.png"},
    {id: 487, name: "Giratina", tipo: ["Fantasma", "Dragão"], fraqueza: ["Gelo", "Dragão", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/487.png"},
    {id: 488, name: "Cresselia", tipo: ["Psiquico"], fraqueza: ["Inseto", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/488.png"},
    {id: 491, name: "Darkrai", tipo: ["Sombrio"], fraqueza: ["Luta", "Inseto", "Fada"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/491.png"},
    {id: 492, name: "Shaymin", tipo: ["Planta"], fraqueza: ["Fogo", "Gelo", "Venenoso", "Voador", "Inseto"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/492.png"},
    {id: 493, name: "Arceus", tipo: ["Normal"], fraqueza: ["Luta"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/493.png"},
    {id: 494, name: "Victini", tipo: ["Psiquico", "Fogo"], fraqueza: ["Agua", "Terra", "Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/494.png"},
    {id: 638, name: "Cobalion", tipo: ["Aço", "Luta"], fraqueza: ["Fogo", "Luta", "Terra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/638.png"},
    {id: 639, name: "Terrakion", tipo: ["Pedra", "Luta"], fraqueza: ["Agua", "Planta", "Luta", "Terra", "Psiquico", "Fada"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/639.png"},
    {id: 640, name: "Virizion", tipo: ["Planta", "Luta"], fraqueza: ["Fogo", "Gelo", "Venenoso", "Voador", "Psiquico", "Fada"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/640.png"},
    {id: 641, name: "Tornadus", tipo: ["Voador"], fraqueza: ["Elétrico", "Gelo", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/641.png"},
    {id: 642, name: "Thundurus", tipo: ["Elétrico", "Voador"], fraqueza: ["Gelo", "Pedra"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/642.png"},
    {id: 645, name: "Landorus", tipo: ["Terra", "Voador"], fraqueza: ["Agua", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/645.png"},
    {id: 716, name: "Xerneas", tipo: ["Fada"], fraqueza: ["Venenoso", "Aço"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/716.png"},
    {id: 717, name: "Yveltal", tipo: ["Sombrio", "Voador"], fraqueza: ["Elétrico", "Gelo", "Pedra", "Fada"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/717.png"},
    {id: 718, name: "Zygarde", tipo: ["Dragão", "Terra"], fraqueza: ["Gelo", "Dragão", "Fada"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/718.png"},
    {id: 720, name: "Hoopa", tipo: ["Psiquico", "Fantasma"], fraqueza: ["Fantasma", "Sombrio"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/720.png"},
    {id: 822, name: "Corvisquire", tipo: ["Voador"], fraqueza: ["Elétrico", "Pedra", "Gelo"], imagem: "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/822.png"}
]